In [1]:
import pandas as pd
from openpyxl import load_workbook
from sklearn import preprocessing as pre
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error

In [7]:
df = load_workbook(filename="Data Alumni.xlsx")
rangesheet = df['Sheet5']
column = ['no','nim','nama','ttl','fakultas_ketrampilan','alamat','tahun_masuk','tahun_lulus','status_pekerjaan','lama_masa_tunggu','gaji_pertama','toefl','ipk']
d = pd.DataFrame(rangesheet.values,columns=column)
d = d[1:]
d

no       nim                  nama                               ttl  \
1    1   9018263      Puguh Drajat E.P        Purworejo, 4 November 1989   
2    2  12022030  Arsyad Cahya Subrata              Bantul, 21 juni 1994   
3    3  12020021          Yesi Novela          Tempilang, 1 januari 1995   
4    4   9018269       Pandu Herwijaya         Lampung, 19 Desember 1990   
5    5   9018109        Anjar Prasetyo        Gunungkidul, 27 April 1991   
6    6   9020026   Moh. Dadi Kurniawan         Savanajaya, 27 Maret 1992   
7    7  12018060        Martin Sarlina              Lepak, 23 Maret 1994   
8    8  11018022      Yan Adhi Permadi              Jepara, 22 juni 1993   
9    9   9018212       Achicha Wahyuni           Yogyakarta, 3 juni 1991   
10  10   9018301   Yayan Tisna Permadi      Purbalingga, 08 Oktober 1991   
11  11  12022020        Muh. Rama dhai          Pekanbaru, 29 Maret 1992   
12  12  12022038           Nurwahyuddi  Dili, timor-timur/ 13 April 1995   
13  13  12019039          Agus Purnomo            Klaten, 2 Agustus 1992   
14  14  11018111  M. Akhwan Zulfayandi          Teros, 12 September 1992   
15  15   9018135   Yunita Tri Hernawai            Magelang, 20 Juni 1991   
16  16  12018161     Pratama Setya Aji         Sleman, 20 September 1994   

       fakultas_ketrampilan  \
1   FTI / Teknik Iformatika   
2      FTI / Teknik Elektro   
3                       FTI   
4    FTI/ Teknik Infomatika   
5   FTI /Teknik Informatika   
6              FTI / Futsal   
7                       FTI   
8                       FTI   
9           FTI/ Web Design   
10   FTI/ Teknik Inormatika   
11     FTI / Teknik Elektro   
12     FTI / Teknik Elektro   
13     FTI/ Teknik Industri   
14  FTI/ Teknik Informatika   
15  FTI/ Teknik Informatika   
16                      FTI   

                                               alamat tahun_masuk tahun_lulus  \
1                                 Tangerang Rt. 01/ 0        2009        2016   
2    Karangpule Rt.01 , Tirtonirmolo , Kasihan Bantul        2012        2016   
3                                                None        2012        2016   
4                         Tamantirto, Kasihan ,Bantul        2009        2016   
5                             Umbulharjo , Yogyakarta        2009        2016   
6                   Saren Rt. 02 Rw. 01 Caturtunggal         2009        2016   
7                                                 NTB        2012        2016   
8                                        Umbulharjo V        2011        2016   
9                     Noyokerten, Sendangirto, Berbah        2009        2016   
10                       Tajug, Rt.04/ 05 Purbalingga        2009        2016   
11     Karongan Rt/Rw. 04/11 Jogotirto, Berbah Sleman        2012        2016   
12                 Juru Gentong J V/407 C Banguntapan        2012        2016   
13                      Dukuh Glagahwangi, Polanharjo        2012        2016   
14  Jl. Peumnas gg. Indragiri Blok B/24, Condongcatur        2011        2016   
15                                           Magelang        2009        2016   
16           Jl. Affandi gg.Kamboja CTX.19 Yogyakarta        2012        2016   

   status_pekerjaan lama_masa_tunggu gaji_pertama toefl   ipk  
1              None              2.4  1.47563e+06   390  2,13  
2              None             None         None  None  None  
3         Mahasiswa              2.4  1.47563e+06  None  None  
4              None              2.4      1475634   413  2,75  
5              None             None         None  None  None  
6              None              2.4  1.47563e+06   400  3,24  
7              None              2.4  1.47563e+06   396  3,27  
8        Wiraswasta              2.4  1.47563e+06   460  3,20  
9              Guru                0       600000   403  3,24  
10             None              2.4  1.47563e+06   450  3,06  
11             None              2.4      1200000   423  3.47  
12        Mahasiswa              2.4 

In [9]:
da=d[['tahun_masuk','tahun_lulus','toefl']]
da.columns = ['tahun_masuk','tahun_lulus','toefl']
da = da.dropna(axis=0, how='any')
da['toefl'].astype(str).astype(int)
da

tahun_masuk tahun_lulus toefl
1         2009        2016   390
4         2009        2016   413
6         2009        2016   400
7         2012        2016   396
8         2011        2016   460
9         2009        2016   403
10        2009        2016   450
11        2012        2016   423
12        2012        2016   413
13        2012        2016   480
14        2011        2016   406
15        2009        2016   423
16        2012        2016   400

In [10]:
print(da.dtypes) #cek type data

tahun_masuk    object
tahun_lulus    object
toefl          object
dtype: object


In [11]:
for index, row in da.iterrows(): 
   
    da.loc[index, 'masa_studi'] = row['tahun_lulus'] - row['tahun_masuk']
da

tahun_masuk tahun_lulus toefl  masa_studi
1         2009        2016   390         7.0
4         2009        2016   413         7.0
6         2009        2016   400         7.0
7         2012        2016   396         4.0
8         2011        2016   460         5.0
9         2009        2016   403         7.0
10        2009        2016   450         7.0
11        2012        2016   423         4.0
12        2012        2016   413         4.0
13        2012        2016   480         4.0
14        2011        2016   406         5.0
15        2009        2016   423         7.0
16        2012        2016   400         4.0

In [12]:
d_train = da[['toefl','masa_studi']].reset_index(drop=True) 
d_train

toefl  masa_studi
0    390         7.0
1    413         7.0
2    400         7.0
3    396         4.0
4    460         5.0
5    403         7.0
6    450         7.0
7    423         4.0
8    413         4.0
9    480         4.0
10   406         5.0
11   423         7.0
12   400         4.0

In [13]:
# targetnya predikat
tar = d_train['masa_studi'].values 
tar

array([7., 7., 7., 4., 5., 7., 7., 4., 4., 4., 5., 7., 4.])

In [14]:
columns = ['toefl']
features = d_train[list(columns)].values
features

array([[390],
       [413],
       [400],
       [396],
       [460],
       [403],
       [450],
       [423],
       [413],
       [480],
       [406],
       [423],
       [400]], dtype=object)

In [15]:
scaler = pre.StandardScaler().fit(features) #menyiapkan feature training 
x = scaler.transform(features)
x

array([[-1.13289699],
       [-0.25760965],
       [-0.75233728],
       [-0.90456116],
       [ 1.531021  ],
       [-0.63816936],
       [ 1.15046129],
       [ 0.12295006],
       [-0.25760965],
       [ 2.29214042],
       [-0.52400145],
       [ 0.12295006],
       [-0.75233728]])

In [18]:
scaler = pre.StandardScaler().fit(features) #menyiapkan feature training 
y = scaler.transform(features)
y

array([[-1.13289699],
       [-0.25760965],
       [-0.75233728],
       [-0.90456116],
       [ 1.531021  ],
       [-0.63816936],
       [ 1.15046129],
       [ 0.12295006],
       [-0.25760965],
       [ 2.29214042],
       [-0.52400145],
       [ 0.12295006],
       [-0.75233728]])

In [19]:

SVR_model = SVR(kernel = 'linear', C=100, gamma=.001).fit(x,y) 
SVR_model

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=100, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.001,
    kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [20]:
data_test = d_train.sample(n=10)
data_test

toefl  masa_studi
3    396         4.0
8    413         4.0
10   406         5.0
5    403         7.0
1    413         7.0
7    423         4.0
0    390         7.0
9    480         4.0
6    450         7.0
12   400         4.0

In [21]:
columns = ['toefl']
feature_test = data_test[list(columns)].values
feature_test

array([[396],
       [413],
       [406],
       [403],
       [413],
       [423],
       [390],
       [480],
       [450],
       [400]], dtype=object)

In [22]:
scalertest = pre.StandardScaler().fit(feature_test)
test_data= scalertest.transform(feature_test)
test_data

array([[-0.81466046],
       [-0.16750028],
       [-0.433978  ],
       [-0.54818274],
       [-0.16750028],
       [ 0.21318218],
       [-1.04306994],
       [ 2.3830722 ],
       [ 1.24102482],
       [-0.66238748]])

In [23]:
predict = SVR_model.predict(test_data)
predict

array([-0.73324339, -0.12387318, -0.37479032, -0.48232624, -0.12387318,
        0.23457989, -0.94831523,  2.27776235,  1.20240316, -0.58986216])

In [24]:
ytrue = data_test['masa_studi'].values
ytrue

array([4., 4., 5., 7., 7., 4., 7., 4., 7., 4.])

# MAPE

In [25]:
import numpy as np 

def mean_absolute_percentage_error(y_true, predict):
    y_true, predict = np.array(y_true),np.array(predict)
    return np.mean(np.abs((y_true-predict))*100)

In [27]:
 mean_absolute_percentage_error(ytrue, predict)

526.6153829378854

# PROSES MSE

In [28]:
from sklearn.metrics import mean_squared_error 

In [29]:
ytrue_mse = data_test['masa_studi'].values
ytrue_mse

array([4., 4., 5., 7., 7., 4., 7., 4., 7., 4.])

In [31]:
mean_squared_error(ytrue_mse, predict)

31.00322388425655

# PROSES MAD

In [33]:
mean_absolute_error(ytrue,predict)

5.2661538293788555